name: "Stratus Testrail Reporter"
description: "Stratus Testrail Reporter"
author: "Q4Inc"
inputs:
  regression_mode:
    required: false
    description: Used in git development flow. This will determine whether or not to leverage milestones to track regression
  network_url:
    required: false
    description: The Testrail account domain name
    default: "https://q4web.testrail.com"
  username:
    required: false
    description: The username associated with the test runner
    default: "app@q4inc.com"
  api_key:
    required: true
    description: The API key associated with the username
  project_id:
    required: false
    description: The project ID of the Testrail project
  suite_id:
    required: false
    description: The suite ID of the Testrail project
  report_results:
    required: false
    description: A boolean to report results to the presenter
    default: "false"
  close_milestone:
    description: Make sure testrail milestone will get closed after production pipeline is completed.
    required: false
    type: boolean
    default: false
outputs:
  test_runs:
    value: ${{ steps.report.outputs.test_runs }}
    description: The result of the test runs

runs:
  using: "composite"
  steps:
    - name: find_pull_request
      uses: juliangruber/find-pull-request-action@v1.8.0
      id: find_pull_request
      with:
        branch: ${{ github.ref_name }}

    - id: jira-key-match
      uses: q4mobile/action-regex-match@v2.0.2-q4-0.0.1
      with:
        #Feature Branch uses pull request title: steps.find_pull_request.outputs.title
        #Main Branch uses commit message: github.event.head_commit.message
        text: ${{ steps.find_pull_request.outputs.title || github.event.head_commit.message }}
        regex: '(?<=(feat|fix|docs|style|refactor|perf|test|chore)\()[^)]+(?=\))'
        flags: gm

    - name: checkout
      uses: actions/checkout@v3.5.2
      with:
        repository: q4mobile/stratus-testrail-reporter
        path: ./.github/actions/stratus-testrail-reporter
        ref: v12.2

    - uses: ./.github/actions/stratus-testrail-reporter/main
      id: report
      env:
        NODE_ENV: ${{ env.NODE_ENV }}
      with:
        regression_mode: ${{ inputs.regression_mode }}
        network_url: ${{ inputs.network_url }}
        username: ${{ inputs.username }}
        api_key: ${{ inputs.api_key }}
        project_id: ${{ inputs.project_id }}
        suite_id: ${{ inputs.suite_id }}
        jira_key: ${{ steps.jira-key-match.outputs.match }}
        close_milestone: ${{ inputs.close_milestone }}

    - if: inputs.report_results == 'true'
      id: result
      uses: q4mobile/stratus-testrail-presenter@v3
      with:
        api_key: ${{ inputs.api_key }}
        network_url: ${{ inputs.network_url }}
        test_runs: ${{ steps.report.outputs.test_runs }}
        username: ${{ inputs.username }}
        current_branch: ${{ github.ref_name }}
